import { CreditCard, Headset, Package, Trophy } from "lucide-react";
import { MarketplaceImages } from "../constants/image";

export const HOMEPLACEMARKETPLACE = [
  {
    id: 1,
    name: "Wireless Bluetooth Headphones",
    description:
      "Noise-cancelling over-ear headphones with 40-hour battery life.",
    price: 99.99,
    category: "Electronics",
    image: "/images/products/headphones.jpg",
    stock: 42,
    rating: 4.5,
  },
  {
    id: 2,
    name: "Smart Watch Series 5",
    description: "Fitness tracker with heart rate monitor and GPS.",
    price: 149.99,
    category: "Wearables",
    image: "/images/products/smartwatch.jpg",
    stock: 18,
    rating: 4.2,
  },
  {
    id: 3,
    name: "Gaming Laptop RTX 4070",
    description: "High-performance laptop with 16GB RAM and 1TB SSD.",
    price: 1299.0,
    category: "Computers",
    image: "/images/products/laptop.jpg",
    stock: 5,
    rating: 4.8,
  },
  {
    id: 4,
    name: "Electric Standing Desk",
    description: "Adjustable height desk with memory presets.",
    price: 399.99,
    category: "Furniture",
    image: "/images/products/desk.jpg",
    stock: 10,
    rating: 4.6,
  },
  {
    id: 5,
    name: '4K Ultra HD TV 55"',
    description: "Smart TV with HDR10+ and voice control.",
    price: 599.99,
    category: "Electronics",
    image: "/images/products/tv.jpg",
    stock: 20,
    rating: 4.7,
  },
  {
    id: 6,
    name: "Mechanical Keyboard RGB",
    description: "Hot-swappable keys and full RGB lighting.",
    price: 89.99,
    category: "Accessories",
    image: "/images/products/keyboard.jpg",
    stock: 25,
    rating: 4.4,
  },
  {
    id: 7,
    name: "Noise Cancelling Earbuds",
    description: "Compact earbuds with wireless charging case.",
    price: 69.99,
    category: "Audio",
    image: "/images/products/earbuds.jpg",
    stock: 32,
    rating: 4.3,
  },
  {
    id: 8,
    name: "Smart Home Security Camera",
    description: "1080p indoor camera with night vision and motion detection.",
    price: 49.99,
    category: "Home Security",
    image: "/images/products/camera.jpg",
    stock: 50,
    rating: 4.1,
  },
  {
    id: 9,
    name: "Backpack with USB Charging Port",
    description: "Waterproof travel backpack for laptops up to 17”.",
    price: 39.99,
    category: "Bags",
    image: "/images/products/backpack.jpg",
    stock: 40,
    rating: 4.5,
  },
  {
    id: 10,
    name: "Stainless Steel Water Bottle",
    description:
      "Double-walled, vacuum-insulated bottle keeps drinks hot or cold.",
    price: 24.99,
    category: "Lifestyle",
    image: "/images/products/waterbottle.jpg",
    stock: 100,
    rating: 4.9,
  },
  {
    id: 11,
    name: "LED Desk Lamp with USB Port",
    description: "Dimmable lamp with touch control and flexible neck.",
    price: 29.99,
    category: "Home Office",
    image: "/images/products/desk-lamp.jpg",
    stock: 35,
    rating: 4.2,
  },
  {
    id: 12,
    name: "Men's Casual Sneakers",
    description: "Comfortable, stylish shoes for daily wear.",
    price: 54.99,
    category: "Footwear",
    image: "/images/products/sneakers.jpg",
    stock: 60,
    rating: 4.3,
  },
  {
    id: 13,
    name: "Women's Fitness Leggings",
    description: "High-waisted, breathable athletic leggings.",
    price: 34.99,
    category: "Clothing",
    image: "/images/products/leggings.jpg",
    stock: 80,
    rating: 4.6,
  },
  {
    id: 14,
    name: "Ceramic Non-Stick Cookware Set",
    description: "10-piece cookware set with heat-resistant handles.",
    price: 119.99,
    category: "Kitchen",
    image: "/images/products/cookware.jpg",
    stock: 22,
    rating: 4.5,
  },
  {
    id: 15,
    name: "Cordless Vacuum Cleaner",
    description: "Lightweight vacuum with powerful suction and wall mount.",
    price: 159.99,
    category: "Home Appliances",
    image: "/images/products/vacuum.jpg",
    stock: 12,
    rating: 4.4,
  },
  {
    id: 16,
    name: "Smartphone Tripod with Remote",
    description: "Flexible tripod compatible with all phones.",
    price: 19.99,
    category: "Photography",
    image: "/images/products/tripod.jpg",
    stock: 70,
    rating: 4.1,
  },
  {
    id: 17,
    name: "USB-C Multiport Adapter",
    description: "6-in-1 adapter with HDMI, USB 3.0, and card reader.",
    price: 44.99,
    category: "Tech Accessories",
    image: "/images/products/adapter.jpg",
    stock: 55,
    rating: 4.3,
  },
  {
    id: 18,
    name: "Essential Oil Diffuser",
    description: "Ultrasonic cool mist diffuser with 7 LED colors.",
    price: 27.99,
    category: "Wellness",
    image: "/images/products/diffuser.jpg",
    stock: 45,
    rating: 4.4,
  },
  {
    id: 19,
    name: "Ergonomic Office Chair",
    description: "Mesh backrest, adjustable height, and lumbar support.",
    price: 229.99,
    category: "Office Furniture",
    image: "/images/products/office-chair.jpg",
    stock: 8,
    rating: 4.7,
  },
  {
    id: 20,
    name: "Portable Power Bank 20000mAh",
    description: "Fast charging, dual output, and LED battery display.",
    price: 39.99,
    category: "Power",
    image: "/images/products/powerbank.jpg",
    stock: 75,
    rating: 4.6,
  },
];

// shop by brands
export const SHOPBYBRANDS = [
  {
    id: 1,
    image: MarketplaceImages.chairEleven,
    name: "Wireless Bluetooth Headphones",
    description:
      "Experience immersive sound with these over-ear wireless headphones, designed to deliver deep bass and clear highs. With active noise cancellation and up to 40 hours of battery life, they are perfect for long flights, commutes, or work sessions.",
    price: 99.99,
    category: "Electronics",
    stock: 42,
    rating: 4.5,
  },
  {
    id: 2,
    image: MarketplaceImages.chairEight,
    name: "Smart Watch Series 5",
    description:
      "Stay connected and track your health with this sleek smart watch. Featuring a heart rate monitor, sleep tracking, built-in GPS, and notifications, it’s the perfect companion for fitness and everyday productivity.",
    price: 149.99,
    category: "Wearables",
    stock: 18,
    rating: 4.2,
  },
  {
    id: 3,
    image: MarketplaceImages.chairFour,
    name: "Gaming Laptop RTX 4070",
    description:
      "Power through demanding games and creative tasks with this high-performance gaming laptop. Equipped with an RTX 4070 GPU, 16GB RAM, and a 1TB SSD, it offers ultra-fast performance and stunning graphics on a crisp 144Hz display.",
    price: 1299.0,
    category: "Computers",
    stock: 5,
    rating: 4.8,
  },
  {
    id: 4,
    image: MarketplaceImages.chairOne,
    name: "Electric Standing Desk",
    description:
      "Improve your posture and productivity with this electric standing desk. It features smooth height adjustments, programmable memory presets, a spacious surface, and a modern design suitable for home or office use.",
    price: 399.99,
    category: "Furniture",
    stock: 10,
    rating: 4.6,
  },
  // {
  //   id: 5,
  //   image: MarketplaceImages.chairFive,
  //   name: '4K Ultra HD TV 55"',
  //   description:
  //     "Enjoy cinematic visuals at home with this 55-inch 4K Ultra HD Smart TV. With HDR10+ support, vibrant colors, and built-in streaming apps, it’s perfect for movie nights, sports, and next-gen gaming.",
  //   price: 599.99,
  //   category: "Electronics",
  //   stock: 20,
  //   rating: 4.7,
  // },
  // {
  //   id: 6,
  //   image: MarketplaceImages.chairSeven,
  //   name: "Mechanical Keyboard RGB",
  //   description:
  //     "Level up your typing and gaming experience with this mechanical keyboard featuring hot-swappable switches, vibrant RGB lighting, and a solid aluminum frame for durability and aesthetics.",
  //   price: 89.99,
  //   category: "Accessories",
  //   stock: 25,
  //   rating: 4.4,
  // },
];

// trending products.
export const TRENDINGPRODUCTS = [
  {
    id: 1,
    image: MarketplaceImages.chairMain,
    name: "Wireless Bluetooth Headphones",
    description:
      "Experience immersive sound with these over-ear wireless headphones, designed to deliver deep bass and clear highs. With active noise cancellation and up to 40 hours of battery life, they are perfect for long flights, commutes, or work sessions.",
    price: 99.99,
    category: "Electronics",
    stock: 42,
    rating: 4.5,
  },
  {
    id: 2,
    image: MarketplaceImages.chairNine,
    name: "Smart Watch Series 5",
    description:
      "Stay connected and track your health with this sleek smart watch. Featuring a heart rate monitor, sleep tracking, built-in GPS, and notifications, it’s the perfect companion for fitness and everyday productivity.",
    price: 149.99,
    category: "Wearables",
    stock: 18,
    rating: 4.2,
  },
  {
    id: 3,
    image: MarketplaceImages.chairFive,
    name: "Gaming Laptop RTX 4070",
    description:
      "Power through demanding games and creative tasks with this high-performance gaming laptop. Equipped with an RTX 4070 GPU, 16GB RAM, and a 1TB SSD, it offers ultra-fast performance and stunning graphics on a crisp 144Hz display.",
    price: 1299.0,
    category: "Computers",
    stock: 5,
    rating: 4.8,
  },
  {
    id: 4,
    image: MarketplaceImages.chairThree,
    name: "Electric Standing Desk",
    description:
      "Improve your posture and productivity with this electric standing desk. It features smooth height adjustments, programmable memory presets, a spacious surface, and a modern design suitable for home or office use.",
    price: 399.99,
    category: "Furniture",
    stock: 10,
    rating: 4.6,
  },
  // {
  //   id: 5,
  //   image: MarketplaceImages.chairFive,
  //   name: '4K Ultra HD TV 55"',
  //   description:
  //     "Enjoy cinematic visuals at home with this 55-inch 4K Ultra HD Smart TV. With HDR10+ support, vibrant colors, and built-in streaming apps, it’s perfect for movie nights, sports, and next-gen gaming.",
  //   price: 599.99,
  //   category: "Electronics",
  //   stock: 20,
  //   rating: 4.7,
  // },
  // {
  //   id: 6,
  //   image: MarketplaceImages.chairSeven,
  //   name: "Mechanical Keyboard RGB",
  //   description:
  //     "Level up your typing and gaming experience with this mechanical keyboard featuring hot-swappable switches, vibrant RGB lighting, and a solid aluminum frame for durability and aesthetics.",
  //   price: 89.99,
  //   category: "Accessories",
  //   stock: 25,
  //   rating: 4.4,
  // },
];

export const SUBANNERHELPERS = [
  {
    banner: "Fast delivery",
    subtext: "Fast delivery in 24hours",
    icon: Package,
  },
  {
    banner: "24 Hours Return",
    subtext: "100% Money back guarantee",
    icon: Trophy,
  },
  {
    banner: "Secure Payment",
    subtext: "Transactions are safe",
    icon: CreditCard,
  },
  {
    banner: "24/7 Support",
    subtext: "Everystep of the way",
    icon: Headset,
  },
];
